/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectorencar;

import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class De_Reservas_Clientes extends javax.swing.JFrame {
    private final String usuario;
    private final int nivelUsuario;
    private final String nombre;
    private final String apellido;
    
    
    
    private final boolean modoCreando = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(De_Reservas_Clientes.class.getName());

    /**
     * Creates new form De_Reservas_Clientes
     * @param usuario
     * @param nivel
     * @param apellido
     * @param nombre
     */
    public De_Reservas_Clientes(String usuario, int nivel, String nombre, String apellido) {
        initComponents(); 
        
        this.usuario = usuario;
        this.nivelUsuario = nivel;
        this.nombre = nombre;
        this.apellido = apellido;
        
        
        
        jPanel1.setPreferredSize(new java.awt.Dimension(781, 1231));
        java.time.LocalDate hoy = java.time.LocalDate.now();
        lblFechaReserva.setText(hoy.toString());
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                volverAlMenu();
            }
        });
    }
    
    
    
  private void cargarVehiculoYOferta() {
        String matricula = txtIdMatricula.getText().trim();
        if (matricula.isEmpty()) return;

        String[] vehiculo = ArchivoUtil.buscarVehiculo(matricula);

        if (vehiculo != null) {

            boolean status = vehiculo[13].trim().equalsIgnoreCase("true");

            lblMarcaModelo.setText(vehiculo[1] + " " + vehiculo[2]);
            lblDescVeh.setText(vehiculo[6]);

            if (status) {
                jRadioButton1.setText("Disponible");
                jRadioButton1.setSelected(true);
            } else {
                jRadioButton1.setText("No Disponible");
                jRadioButton1.setSelected(false);
            }

            String[] oferta = ArchivoUtil.buscarOfertaPorMatricula(matricula);

            if (oferta != null) {
                txtIdOferta.setText(oferta[0]);
                lblPrecioOferta.setText("RD$ " + oferta[3]);
            } else {
                txtIdOferta.setText("");
                lblPrecioOferta.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Matrícula no existe.");
            txtIdMatricula.setText("");
        }
    }

    private void volverAlMenu() {
        new MenuPrincipal(usuario, nivelUsuario, nombre, apellido).setVisible(true);
        this.dispose();
    }
 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdMatricula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblMarcaModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblDescVeh = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtreserva = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtIdCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblNombreCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdOferta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblPrecioOferta = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblFechaReserva = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFechaSalida = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtFechaEntrada = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lblDiasReserva = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblTotalReserva = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtObservacion = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(30, 159, 117));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Reserva de Clientes");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel11.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 159, 117)));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("VEHÍCULOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Matrícula");

        txtIdMatricula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        txtIdMatricula.addActionListener(this::txtIdMatriculaActionPerformed);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Marca / Modelo");

        lblMarcaModelo.setEditable(false);
        lblMarcaModelo.setBackground(new java.awt.Color(239, 239, 255));
        lblMarcaModelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        lblMarcaModelo.setOpaque(true);
        lblMarcaModelo.addActionListener(this::lblMarcaModeloActionPerformed);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Descripción");

        lblDescVeh.setEditable(false);
        lblDescVeh.setBackground(new java.awt.Color(239, 239, 255));
        lblDescVeh.setToolTipText("");
        lblDescVeh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Id de Reserva");

        txtreserva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        txtreserva.addActionListener(this::txtreservaActionPerformed);

        jRadioButton1.setBackground(new java.awt.Color(0, 153, 51));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Disponible");
        jRadioButton1.setOpaque(true);
        jRadioButton1.addActionListener(this::jRadioButton1ActionPerformed);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Status de Vehiculo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMarcaModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel3))
                            .addComponent(txtreserva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(lblDescVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(133, 133, 133))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(599, 599, 599))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtreserva, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescVeh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarcaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 159, 117), 1, true));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("CLIENTE");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Cédula");

        txtIdCedula.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        txtIdCedula.addActionListener(this::txtIdCedulaActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nombre del Cliente");

        lblNombreCliente.setEditable(false);
        lblNombreCliente.setBackground(new java.awt.Color(239, 239, 255));
        lblNombreCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(txtIdCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 159, 117), 1, true));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("OFERTA (opcional)");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ID Oferta");

        txtIdOferta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        txtIdOferta.addActionListener(this::txtIdOfertaActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Precio de la Oferta");

        lblPrecioOferta.setEditable(false);
        lblPrecioOferta.setBackground(new java.awt.Color(239, 239, 255));
        lblPrecioOferta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        lblPrecioOferta.addActionListener(this::lblPrecioOfertaActionPerformed);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(txtIdOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(lblPrecioOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdOferta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 159, 117), 1, true));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("FECHAS Y CÁLCULOS");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Fecha de Reserva");

        lblFechaReserva.setEditable(false);
        lblFechaReserva.setBackground(new java.awt.Color(204, 255, 204));
        lblFechaReserva.setBorder(null);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Fecha de Salida");

        txtFechaSalida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Fecha de Entrada");

        txtFechaEntrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        txtFechaEntrada.addActionListener(this::txtFechaEntradaActionPerformed);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Días de Reserva");

        lblDiasReserva.setEditable(false);
        lblDiasReserva.setBackground(new java.awt.Color(204, 255, 204));
        lblDiasReserva.setBorder(null);
        lblDiasReserva.addActionListener(this::lblDiasReservaActionPerformed);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Total a Pagar");

        lblTotalReserva.setEditable(false);
        lblTotalReserva.setBackground(new java.awt.Color(156, 189, 255));
        lblTotalReserva.setBorder(null);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lblFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 45, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(lblDiasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(lblTotalReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechaReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiasReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 159, 117), 1, true));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 255));
        jLabel18.setText("OBSERVACIÓN");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Observación");

        txtObservacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 255), 1, true));
        txtObservacion.addActionListener(this::txtObservacionActionPerformed);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 0));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnGuardar.setBackground(new java.awt.Color(0, 0, 255));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar ");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMatriculaActionPerformed
    String matricula = txtIdMatricula.getText().trim();
    if (matricula.isEmpty()) return;

    cargarVehiculoYOferta(); 
    String[] vehiculo = ArchivoUtil.buscarVehiculo(matricula);

    if (vehiculo != null) {

        // true = Disponible, false = No disponible
        boolean status = vehiculo[13].trim().equalsIgnoreCase("true");

        // CARGAR DATOS
        lblMarcaModelo.setText(vehiculo[1] + " " + vehiculo[2]);
        lblDescVeh.setText(vehiculo[6]);

        // MOSTRAR STATUS CORRECTO
        if (status) {
            jRadioButton1.setText("Disponible");
            jRadioButton1.setSelected(true);
        } else {
            jRadioButton1.setText("No Disponible");
            jRadioButton1.setSelected(false);
        }

        // VALIDAR SI NO ESTÁ DISPONIBLE
        if (!status) {
            JOptionPane.showMessageDialog(this, "Este vehículo no está disponible.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // BUSCAR OFERTA
        String[] oferta = ArchivoUtil.buscarOfertaPorMatricula(matricula);

        if (oferta != null) {
            txtIdOferta.setText(oferta[0]);
            lblPrecioOferta.setText("RD$ " + oferta[3]);
        } else {
            txtIdOferta.setText("");
            lblPrecioOferta.setText("");
        }

    } else {
        JOptionPane.showMessageDialog(this, "Matrícula no existe.");
        txtIdMatricula.setText("");
        jRadioButton1.setSelected(false);
        jRadioButton1.setText("Disponible");
    }


    
    }//GEN-LAST:event_txtIdMatriculaActionPerformed

    private void lblMarcaModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblMarcaModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblMarcaModeloActionPerformed

    private void lblPrecioOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblPrecioOfertaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblPrecioOfertaActionPerformed

    private void txtFechaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEntradaActionPerformed
    try {
        java.time.LocalDate salida = java.time.LocalDate.parse(txtFechaSalida.getText().trim());
        java.time.LocalDate entrada = java.time.LocalDate.parse(txtFechaEntrada.getText().trim());
        java.time.LocalDate reserva = java.time.LocalDate.parse(lblFechaReserva.getText());

        if (salida.isBefore(reserva)) {
            JOptionPane.showMessageDialog(this, "Fecha salida menor que fecha reserva");
            return;
        }

        if (entrada.isBefore(salida)) {
            JOptionPane.showMessageDialog(this, "La fecha de entrada no puede ser antes de la salida.");
            return;
        }

        long dias = java.time.temporal.ChronoUnit.DAYS.between(salida, entrada);
        lblDiasReserva.setText(dias + " días");

        String idOferta = txtIdOferta.getText().trim();
        double precio;

        if (!idOferta.isEmpty() && ArchivoUtil.buscarOferta(idOferta) != null) {
            precio = Double.parseDouble(ArchivoUtil.buscarOferta(idOferta)[3]);
        } else {
            String[] vehiculo = ArchivoUtil.buscarVehiculo(txtIdMatricula.getText().trim());
            precio = Double.parseDouble(vehiculo[7]);
        }

        double total = precio * dias;
        lblTotalReserva.setText("RD$ " + total);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Formato de fecha inválido (YYYY-MM-DD)");
    }

    }//GEN-LAST:event_txtFechaEntradaActionPerformed

    private void lblDiasReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblDiasReservaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDiasReservaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarTodo();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtObservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtObservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtObservacionActionPerformed

    private void txtIdCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCedulaActionPerformed
        String cedula = txtIdCedula.getText().trim();
        if (cedula.isEmpty()) return;

        String[] cliente = ArchivoUtil.buscarCliente(cedula);

        if (cliente != null) {
            lblNombreCliente.setText(cliente[1] + " " + cliente[2]);
        } else {
            JOptionPane.showMessageDialog(this, "Cliente no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            txtIdCedula.setText("");
        }
    }//GEN-LAST:event_txtIdCedulaActionPerformed

    private void txtIdOfertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdOfertaActionPerformed
    String idOferta = txtIdOferta.getText().trim();

    if (!idOferta.isEmpty()) {
        String[] oferta = ArchivoUtil.buscarOferta(idOferta);

        if (oferta != null) {
            lblPrecioOferta.setText("RD$ " + oferta[3]);
        } else {
            JOptionPane.showMessageDialog(this, "Oferta no existe.");
            txtIdOferta.setText("");
            lblPrecioOferta.setText("");
        }
    }

    }//GEN-LAST:event_txtIdOfertaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtIdMatricula.getText().trim().isEmpty() ||
            txtIdCedula.getText().trim().isEmpty() ||
            txtFechaSalida.getText().trim().isEmpty() ||
            txtFechaEntrada.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos obligatorios.");
            return;
        }
        
        
     
        String matricula = txtIdMatricula.getText().trim();
        String[] vehiculo = ArchivoUtil.buscarVehiculo(matricula);

        if (vehiculo == null) {
            JOptionPane.showMessageDialog(this, "Vehículo no existe.");
            return;
        }

        if (vehiculo[13].equals("false")) {
            JOptionPane.showMessageDialog(this, "Vehículo no disponible.");
            return;
        }

        
        if (txtreserva.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar ID de Reserva.");
            return;
        }if (ArchivoUtil.buscarCliente(txtIdCedula.getText().trim()) == null) {
            JOptionPane.showMessageDialog(this, "Cliente no válido.");
            return;

        }

                String cedula     = txtIdCedula.getText().trim();
                String idOferta   = txtIdOferta.getText().trim();
                String fechaRes   = lblFechaReserva.getText();
                String fechaSal   = txtFechaSalida.getText().trim();
                String fechaEnt   = txtFechaEntrada.getText().trim();
                String dias       = lblDiasReserva.getText().replace(" días", "");
                String total      = lblTotalReserva.getText().replace("RD$ ", "");
                String obs        = txtObservacion.getText().trim();

                String idReserva = txtreserva.getText().trim();

        String nuevaLinea = idReserva + ";" + matricula + ";" + cedula + ";" + idOferta + ";" +
                fechaRes + ";" + fechaSal + ";" + fechaEnt + ";" +
                obs + ";" + dias + ";" + total + ";" + "true";

                ArchivoUtil.agregarLinea("reservas.txt", nuevaLinea);
                cambiarStatusVehiculo(matricula, true);
                JOptionPane.showMessageDialog(this, "Reserva guardada correctamente.");
                limpiarTodo();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    String idReserva = txtreserva.getText().trim();

    if (idReserva.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el ID de reserva a eliminar.");
        return;
    }

    int opcion = JOptionPane.showConfirmDialog(this,
            "¿Seguro que deseas eliminar esta reserva?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

    if (opcion != JOptionPane.YES_OPTION) {
        return;
    }

    borrarReserva(idReserva);  
   
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtreservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreservaActionPerformed
    String id = txtreserva.getText().trim();
    if (id.isEmpty()) return;

    String[] reserva = buscarReserva(id);

    if (reserva != null) {

        // CARGAR DATOS
        txtIdMatricula.setText(reserva[1]);
        txtIdCedula.setText(reserva[2]);
        txtIdOferta.setText(reserva[3]);
        lblFechaReserva.setText(reserva[4]);
        txtFechaSalida.setText(reserva[5]);
        txtFechaEntrada.setText(reserva[6]);
        txtObservacion.setText(reserva[7]);
        lblDiasReserva.setText(reserva[8] + " días");
        lblTotalReserva.setText("RD$ " + reserva[9]);

        String[] vehiculo = ArchivoUtil.buscarVehiculo(reserva[1]);

        if (vehiculo != null) {
            lblMarcaModelo.setText(vehiculo[1] + " " + vehiculo[2]);
            lblDescVeh.setText(vehiculo[6]);

            boolean status = vehiculo[13].trim().equalsIgnoreCase("true");

            if (status) {
                jRadioButton1.setText("Disponible");
                jRadioButton1.setSelected(true);
            } else {
                jRadioButton1.setText("No Disponible");
                jRadioButton1.setSelected(false);
            }
        }

        // CARGAR CLIENTE
        String[] cliente = ArchivoUtil.buscarCliente(reserva[2]);

        if (cliente != null) {
            lblNombreCliente.setText(cliente[1] + " " + cliente[2]);
        }

        // CARGAR OFERTA
        if (!reserva[3].isEmpty()) {
            String[] oferta = ArchivoUtil.buscarOferta(reserva[3]);

            if (oferta != null) {
                lblPrecioOferta.setText("RD$ " + oferta[3]);
            }
        }

    } else {
        JOptionPane.showMessageDialog(this, "Reserva no encontrada");
        txtreserva.setText("");
    }
        
        
        
        
        
        
    }//GEN-LAST:event_txtreservaActionPerformed

    
    private String[] buscarReserva(String idReserva) {
    List<String> lineas = ArchivoUtil.leerArchivo("reservas.txt");

    for (String linea : lineas) {
        String[] datos = linea.split(";");

        if (datos[0].equals(idReserva)) {
            return datos;
        }
    }
    return null;
    
    }
    
    private void borrarReserva(String idReserva) {

    if (nivelUsuario != 0) { // 0 = admin (ajústalo si usas otro nivel)
        JOptionPane.showMessageDialog(this, "Solo el administrador puede borrar.");
        return;
    }

    List<String> lineas = ArchivoUtil.leerArchivo("reservas.txt");
    boolean eliminado = false;
    String matricula = "";

    for (int i = 0; i < lineas.size(); i++) {
        String[] datos = lineas.get(i).split(";");

        if (datos[0].equals(idReserva)) {
            matricula = datos[1]; // guardar matrícula
            lineas.remove(i);
            eliminado = true;
            break;
        }
    
    }
    
    if (eliminado) {
        ArchivoUtil.escribirArchivo("reservas.txt", lineas);

        cambiarStatusVehiculo(matricula, false);

        JOptionPane.showMessageDialog(this, "Reserva eliminada.");
    } else {
        JOptionPane.showMessageDialog(this, "Reserva no encontrada.");
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new De_Reservas_Clientes("Invitado", 1, "Invitado", "Invitado").setVisible(true));
    }
    
    private void cambiarStatusVehiculo(String matricula, boolean status) {
        List<String> lineas = ArchivoUtil.leerArchivo("vehiculos.txt");
        for (int i = 0; i < lineas.size(); i++) {
            String[] partes = lineas.get(i).split(";");
            if (partes[0].equalsIgnoreCase(matricula)) {
                partes[13] = String.valueOf(status);
                lineas.set(i, String.join(";", partes));
                break;
            }
        }
        ArchivoUtil.escribirArchivo("vehiculos.txt", lineas);
        
}
    
    private void limpiarTodo() {
    txtIdMatricula.setText("");
    txtIdCedula.setText("");
    txtIdOferta.setText("");
    txtFechaSalida.setText("");
    txtFechaEntrada.setText("");
    txtObservacion.setText("");
    lblMarcaModelo.setText("");
    lblDescVeh.setText("");
    lblNombreCliente.setText("");
    lblPrecioOferta.setText("");
    lblDiasReserva.setText("");
    lblTotalReserva.setText("");
    java.time.LocalDate hoy = java.time.LocalDate.now();
    lblFechaReserva.setText(hoy.toString());
    txtreserva.setText("");
jRadioButton1.setText("Disponible");
jRadioButton1.setSelected(false);    
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblDescVeh;
    private javax.swing.JTextField lblDiasReserva;
    private javax.swing.JTextField lblFechaReserva;
    private javax.swing.JTextField lblMarcaModelo;
    private javax.swing.JTextField lblNombreCliente;
    private javax.swing.JTextField lblPrecioOferta;
    private javax.swing.JTextField lblTotalReserva;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txtFechaEntrada;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtIdCedula;
    private javax.swing.JTextField txtIdMatricula;
    private javax.swing.JTextField txtIdOferta;
    private javax.swing.JTextField txtObservacion;
    private javax.swing.JTextField txtreserva;
    // End of variables declaration//GEN-END:variables
}
