/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.proyectorencar;

import javax.swing.JOptionPane;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.FileWriter;
import java.io.FileReader;
import java.io.File;
import java.util.Scanner;

    
  


/**
 *
 * @author Owner
 */
public class Deusuario extends javax.swing.JFrame {

    private boolean existe = false;


    // 🔹 AQUÍ VA EL MÉTODO
    public boolean validarUsuario(String user, String pass) {
        try {
            BufferedReader br = new BufferedReader(new FileReader("Usuario.txt"));
            String linea;

            while ((linea = br.readLine()) != null) {
                String[] datos = linea.split(";");

                if (datos[0].equals(user) && datos[1].equals(pass)) {
                    return true;
                }
            }

        } catch (IOException e) {
        }

        return false;
    }

    // resto del código...
    

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Deusuario.class.getName());

    /**
     * Creates new form Deusuario
     */
    public Deusuario() {
        initComponents();
        
        lblMensaje.setText("");//
lblMensaje.setForeground(new java.awt.Color(0, 153, 0)); // verde

    grupoNivel.add(rbNormal);
    grupoNivel.add(rbAdmin);

    lblMensaje.setText("");

    // 🔥 AUTOCOMPLETAR MIENTRAS ESCRIBES
    Usuariotxt.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyReleased(java.awt.event.KeyEvent evt) {
            buscarUsuario(Usuariotxt.getText());
        }
    });

    // 🔥 TAMBIÉN AL SALIR DEL CAMPO
  Usuariotxt.addKeyListener(new java.awt.event.KeyAdapter() {
    @Override
    public void keyReleased(java.awt.event.KeyEvent evt) {
        buscarUsuario(Usuariotxt.getText());

        if (!existe) {
            lblMensaje.setText("Creando nuevo usuario...");
            lblMensaje.setForeground(new java.awt.Color(0, 153, 255));
        }
    }
});
    
}
private void buscarUsuario(String usuario) {

    if (usuario.isEmpty()) return;

    existe = false;

    try (BufferedReader br = new BufferedReader(new FileReader("Usuario.txt"))) {
        String linea;

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");

            if (datos[0].trim().equalsIgnoreCase(usuario.trim())) {

                txtPassword.setText(datos[1]);
                txtNombre.setText(datos[2]);
                txtApellido.setText(datos[3]);
                txtCorreo.setText(datos[5]);

                grupoNivel.clearSelection();
                if (datos[4].trim().equals("0")) {
                    rbAdmin.setSelected(true);
                } else {
                    rbNormal.setSelected(true);
                }

                existe = true;

                lblMensaje.setText("Modificando usuario existente...");
                lblMensaje.setForeground(new java.awt.Color(255, 153, 0));

                return;
            }
        }

        // 🔴 NO EXISTE
        txtPassword.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        grupoNivel.clearSelection();

        lblMensaje.setText("Creando nuevo usuario...");
        lblMensaje.setForeground(new java.awt.Color(0, 153, 255));

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al buscar usuario");
    }
}    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoNivel = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Usuariotxt = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        nivel = new javax.swing.JLabel();
        rbNormal = new javax.swing.JRadioButton();
        rbAdmin = new javax.swing.JRadioButton();
        lblMensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Mantenimiento De Usuario");

        jLabel2.setText("USUARIO");

        jLabel3.setText("CONTRASEÑA");

        Usuariotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UsuariotxtKeyPressed(evt);
            }
        });

        jLabel4.setText("NOMBRE");

        jLabel5.setText("APELLIDO");

        txtApellido.addActionListener(this::txtApellidoActionPerformed);

        jLabel6.setText("CORREO ELECTRONICO");

        btnGuardar.setBackground(new java.awt.Color(0, 0, 255));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnLimpiar.setBackground(new java.awt.Color(0, 204, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnEliminar.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(this::btnEliminarActionPerformed);

        nivel.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        nivel.setForeground(new java.awt.Color(51, 51, 51));
        nivel.setText("NIVEL DE ACCESO:");
        nivel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nivelAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        rbNormal.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbNormal.setForeground(new java.awt.Color(51, 51, 51));
        rbNormal.setText("Normal");
        rbNormal.addActionListener(this::rbNormalActionPerformed);

        rbAdmin.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        rbAdmin.setForeground(new java.awt.Color(51, 51, 51));
        rbAdmin.setText("Administrador");

        lblMensaje.setText("lblMensaje");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCorreo)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Usuariotxt, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(txtApellido))))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(rbNormal)
                                        .addGap(73, 73, 73)
                                        .addComponent(rbAdmin))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(65, 65, 65)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(80, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(nivel)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addGap(30, 30, 30)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivel)
                    .addComponent(rbNormal)
                    .addComponent(rbAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void rbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNormalActionPerformed

    private void nivelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nivelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelAncestorAdded

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    // 🔹 VALIDAR CAMPOS
    if (Usuariotxt.getText().isEmpty() ||
        String.valueOf(txtPassword.getPassword()).isEmpty() ||
        txtNombre.getText().isEmpty() ||
        txtApellido.getText().isEmpty() ||
        txtCorreo.getText().isEmpty()) {

        JOptionPane.showMessageDialog(this, "Complete todos los campos");
        return;
    }

    // 🔹 NIVEL
    String nivel = "";

    if (rbAdmin.isSelected()) {
        nivel = "0";
    } else if (rbNormal.isSelected()) {
        nivel = "1";
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione nivel");
        return;
    }

    try {
        File f = new File("Usuario.txt");

        if (!f.exists()) {
            f.createNewFile();
        }

        String nuevo =
                Usuariotxt.getText() + ";" +
                String.valueOf(txtPassword.getPassword()) + ";" +
                txtNombre.getText() + ";" +
                txtApellido.getText() + ";" +
                nivel + ";" +
                txtCorreo.getText();

        BufferedReader br = new BufferedReader(new FileReader(f));
        String linea;
        StringBuilder contenido = new StringBuilder();

        boolean encontrado = false;

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");

            if (datos[0].equalsIgnoreCase(Usuariotxt.getText())) {
                contenido.append(nuevo).append("\n"); // reemplaza
                encontrado = true;
            } else {
                contenido.append(linea).append("\n");
            }
        }

        br.close();

        // 🔹 SI NO EXISTE → AGREGAR
        if (!encontrado) {
            contenido.append(nuevo).append("\n");
        }

        FileWriter fw = new FileWriter(f);
        fw.write(contenido.toString());
        fw.close();

        // 🔹 MENSAJE
        if (encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario modificado correctamente");
            lblMensaje.setText("Usuario modificado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente");
            lblMensaje.setText("Usuario creado correctamente");
        }

        lblMensaje.setForeground(new java.awt.Color(0, 153, 0));

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar");
    }

    buscarUsuario(Usuariotxt.getText());

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    

    if (Usuariotxt.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese el usuario a eliminar");
        return;
    }

    if (!rbAdmin.isSelected()) {
        JOptionPane.showMessageDialog(this, "Solo el administrador puede eliminar");
        return;
    }

    int opcion = JOptionPane.showConfirmDialog(this,
            "¿Seguro que deseas eliminar este usuario?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION);

    if (opcion == JOptionPane.YES_OPTION) {
        eliminarUsuario(Usuariotxt.getText()); // 👈 LLAMADA AL MÉTODO
    }


      }//GEN-LAST:event_btnEliminarActionPerformed

    
    
    
    
    
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    Usuariotxt.setText("");
    txtPassword.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtCorreo.setText("");
grupoNivel.clearSelection();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
     
        
    }//GEN-LAST:event_jPanel1KeyReleased

    private void UsuariotxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuariotxtKeyPressed
           
    if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
        buscarUsuario(Usuariotxt.getText());
    
    }
       }//GEN-LAST:event_UsuariotxtKeyPressed

// 👇 AQUÍ ABAJO, FUERA DE TODO
private void eliminarUsuario(String usuario) {

    try {
        BufferedReader br = new BufferedReader(new FileReader("Usuario.txt"));
        String linea;
        String contenido = "";

        boolean encontrado = false;

        while ((linea = br.readLine()) != null) {
            String[] datos = linea.split(";");

            if (!datos[0].equals(usuario)) {
         contenido += linea + System.lineSeparator();         
            } else {
                encontrado = true;
            }
        }

        br.close();

        FileWriter fw = new FileWriter("Usuario.txt");
        fw.write(contenido);
        fw.close();

        if (encontrado) {
            JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }

    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar");
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Deusuario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.ButtonGroup grupoNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel nivel;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbNormal;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    

}
