/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectorencar;

import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private final String usuario;
    private final int nivelUsuario;
    private final String nombre;
    private final String apellido;
 
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     * @param usuario
     * @param nivel
     * @param nombre
     * @param apellido
     
     */
  public MenuPrincipal(String usuario, int nivel, String nombre, String apellido) {
    initComponents();
    
    this.usuario = usuario;
    this.nivelUsuario = nivel;
    this.nombre = nombre;
    this.apellido = apellido;
    
    // Configuración de Seguridad [cite: 196, 197]
    if (nivel == 1) { // Usuario Normal
        jMenuItem5.setEnabled(false); // De Goma (Gama)
        jMenuItem6.setEnabled(false); // De Vehículos
        jMenuItem8.setEnabled(false); // De Ofertas
        jMenuItem4.setVisible(false); // Oculta Mantenimiento de Usuarios
        jMenuItem9.setEnabled(false); // De Reserva de Clientes
        jMenuItem1.setEnabled(false); // De Recepción de Vehículo
        // Consultas (solo admin)
        jMenuItem2.setEnabled(false);
        jMenuItem3.setEnabled(false);
        jMenuItem10.setEnabled(false);
        jMenuItem11.setEnabled(false);
        jMenuItem12.setEnabled(false);
    } else { // Administrador (Nivel 0) [cite: 195]
        jMenuItem4.setVisible(true); // El admin sí puede ver "De Usuario"
    }

    setLocationRelativeTo(null);
    lblBienvenida.setText("Bienvenido/a, " + usuario);
    lblMensaje.setText("¡Seleccione una opción del menú para comenzar!");

    // Tu diseño personalizado
    jMenuBar1.setOpaque(true);
    jMenuBar1.setBackground(new java.awt.Color(0, 102, 204));
    jMenuBar1.setUI(new javax.swing.plaf.basic.BasicMenuBarUI());
    jMenuBar1.setPreferredSize(new java.awt.Dimension(0, 50));
    jMenu1.setText("Navegador");
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblBienvenida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBienvenida.setForeground(new java.awt.Color(0, 0, 255));
        lblBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBienvenida.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(204, 204, 255));
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(lblBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 0));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(0, 153, 0));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Navegador");
        jMenu1.setRequestFocusEnabled(false);

        jMenuItem13.setText("Volver a Inicio");
        jMenu1.add(jMenuItem13);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 153, 0));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Mantenimiento");

        jMenuItem4.setText("De Usuario");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("De Gama");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("De Vehículos ");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText(" De Clientes");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("De Ofertas");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        jMenu7.setBackground(new java.awt.Color(0, 153, 0));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setText("Movimiento");
        jMenu7.addActionListener(this::jMenu7ActionPerformed);

        jMenuItem9.setText("De Reservas Clientes");
        jMenuItem9.addActionListener(this::jMenuItem9ActionPerformed);
        jMenu7.add(jMenuItem9);

        jMenuItem1.setText("De Recepción Vehículos");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu7.add(jMenuItem1);

        jMenuBar1.add(jMenu7);

        jMenu3.setBackground(new java.awt.Color(0, 153, 0));
        jMenu3.setForeground(new java.awt.Color(255, 255, 255));
        jMenu3.setText("Consultas");

        jMenuItem2.setText("De Cliente");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("De Vehiculos");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu3.add(jMenuItem3);

        jMenuItem10.setText("De Ofertas");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("De Reservas");
        jMenuItem11.addActionListener(this::jMenuItem11ActionPerformed);
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("De Recepción");
        jMenuItem12.addActionListener(this::jMenuItem12ActionPerformed);
        jMenu3.add(jMenuItem12);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(0, 153, 0));
        jMenu4.setForeground(new java.awt.Color(255, 255, 255));
        jMenu4.setText("Opciones");

        jMenuItem14.setText("Cambiar de Usuario");
        jMenuItem14.addActionListener(this::jMenuItem14ActionPerformed);
        jMenu4.add(jMenuItem14);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(this::MenuSalirActionPerformed);
        jMenu4.add(MenuSalir);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        System.exit(0);    }//GEN-LAST:event_MenuSalirActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        new De_Reservas_Clientes(usuario, nivelUsuario, nombre, apellido).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new DeRecepcionVehiculo(usuario, nivelUsuario, nombre, apellido).setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {
        new com.mycompany.proyectorencar.Consultas.DeClientes().setVisible(true);
    }
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new com.mycompany.proyectorencar.Consultas.DeVehiculos().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {                                           
    new Deusuario(usuario, nivelUsuario, nombre, apellido).setVisible(true);
}

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {
    new DeGama(usuario, nivelUsuario, nombre, apellido).setVisible(true);
}

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {
    new DeVehiculo(usuario, nivelUsuario, nombre, apellido).setVisible(true);
}

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {
    new DeCliente(usuario, nivelUsuario, nombre, apellido).setVisible(true);
}

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {
    new DeOferta(usuario, nivelUsuario, nombre, apellido).setVisible(true);
}

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {
        new com.mycompany.proyectorencar.Consultas.DeOfertas().setVisible(true);
    }
    
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {
        new com.mycompany.proyectorencar.Consultas.DeReservas().setVisible(true);
    }
    
    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {
        new com.mycompany.proyectorencar.Consultas.DeRecepcion().setVisible(true);
    }
    
private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {
     int opcion = JOptionPane.showConfirmDialog(
            this, 
            "¿Deseas cambiar de usuario?", 
            "Cerrar sesión", 
            JOptionPane.YES_NO_OPTION
    );

    if (opcion == JOptionPane.YES_OPTION) {
        // Abrir formulario Login
        Login login = new Login();
        login.setVisible(true);

        // Cerrar ventana actual
        this.dispose(); 
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
java.awt.EventQueue.invokeLater(() -> new MenuPrincipal("Invitado", 1, "Invitado", "Invitado").setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBienvenida;
    private javax.swing.JLabel lblMensaje;
    // End of variables declaration//GEN-END:variables
} 
